<h1>Login Here</h1>
<form action="" method="post" name="login">
    <table>
        <tbody>
        <tr>
            <th>Name:</th>
            <td><input type="text" name="name" required="" /></td>
        </tr>
        <tr>
            <th>Password:</th>
            <td><input type="password" name="password" required="" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" name="submit" value="Login" /></td>
        </tr>
        <tr>
            <td></td>
            <td><a href="registration.php">Register new user</a></td>
        </tr>
        </tbody>
    </table>
</form>
