<h1>Registration Here</h1>
<form action="" method="post" name="reg">
    <table>
        <tbody>
        <tr>
            <th>Category:</th>
            <td><select name="category" required >
                    <option value="father">Father</option>
                    <option value="mother">Mother</option>
                    <option value="child">Child</option>
                </select>
            </td>
        </tr>
        <tr>
            <th>Name:</th>
            <td><input type="text" name="name" required="" /></td>
        </tr>
        <tr>
            <th>Password:</th>
            <td><input type="password" name="upass" required="" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" name="submit" value="Register" /></td>
        </tr>
        <tr>
            <td></td>
            <td><a href="login.php">Already registered! Click Here!</a></td>
        </tr>
        </tbody>
    </table>
</form>